const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const dir=require('node:path').resolve(__dirname,'../..')+'/';
function dom(html){const d=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only'}),w=d.window;w.scrollTo=()=>{};w.setInterval=()=>{};w.requestAnimationFrame=f=>f();w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.HTMLAnchorElement.prototype.click=()=>{};return d}
(async()=>{const v1=fs.readFileSync(dir+'index.html','utf8'),a=dom(v1),w=a.window;
const sessions=[{id:'v1',startedAt:Date.now()-1800000,endedAt:Date.now(),durationMs:1800000,note:'バッハ 🎹'},{id:'long',startedAt:Date.now()-172800000,endedAt:Date.now()-80000000,durationMs:92800000,note:''}];
const original=JSON.stringify({schemaVersion:1,sessions});w.localStorage.setItem('piano-practice-timer-v1',original);let payload;w.Blob=class{constructor(parts){payload=parts.join('')}};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
for(const s of a.window.document.querySelectorAll('script'))if(!s.src)w.eval(s.textContent);w.document.getElementById('exportBackup').click();assert.equal(JSON.parse(payload).sessions.length,2);
const b=dom(fs.readFileSync(dir+'v2/index.html','utf8')),v=b.window;v.localStorage.setItem('piano-practice-timer-v1',original);v.eval(fs.readFileSync(dir+'v2/piano-summary.js','utf8'));v.eval(fs.readFileSync(dir+'v2/piano.js','utf8'));
const input=v.document.getElementById('backupFile');Object.defineProperty(input,'files',{configurable:true,value:[{text:async()=>payload}]});input.dispatchEvent(new v.Event('change'));await new Promise(r=>setImmediate(r));assert.equal(v.document.getElementById('importDialog').open,true);v.document.getElementById('confirmImport').click();assert.equal(v.document.getElementById('dataCount').textContent,'2件');assert.equal(v.localStorage.getItem('piano-practice-timer-v1'),original);assert.deepEqual(JSON.parse(v.localStorage.getItem('piano-practice-timer-v2')).sessions,sessions);
v.document.getElementById('confirmRestore').click();assert.equal(v.document.getElementById('dataCount').textContent,'0件');
Object.defineProperty(input,'files',{value:[{text:async()=>JSON.stringify({version:1,app:'PianoTrack',sessions:[null]})}]});input.dispatchEvent(new v.Event('change'));await new Promise(r=>setImmediate(r));assert.equal(v.document.getElementById('dataCount').textContent,'0件');
console.log('PASS: actual v1 exporter → v2 importer, Unicode notes, >24h sessions, isolated v1 storage, first-import undo, invalid input');a.window.close();b.window.close();})();
