const test=require('node:test'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
function setup({saved={},denied=false}={}){
 const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://example.test/pianotrack/beta/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;let now=1000000000000,db=-20,stopped=0;const loops=[];
 w.Date.now=()=>now;w.scrollTo=()=>{};w.setInterval=fn=>{loops.push(fn);return loops.length};w.clearInterval=id=>{loops[id-1]=null};w.requestAnimationFrame=fn=>fn();w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 const track={stop(){stopped++}};Object.defineProperty(w.navigator,'mediaDevices',{value:{getUserMedia:async()=>{if(denied){const e=new Error('denied');e.name='NotAllowedError';throw e;}return{getTracks:()=>[track]}}}});
 w.AudioContext=class{state='running';createAnalyser(){return{fftSize:2048,getFloatTimeDomainData:array=>array.fill(10**(db/20))}}createMediaStreamSource(){return{connect(){}}}async resume(){}async close(){this.state='closed'}};
 for(const [k,v] of Object.entries(saved))w.localStorage.setItem(k,v);
 for(const name of ['piano-summary.js','autopilot.js','piano.js'])w.eval(fs.readFileSync(path.join(root,name),'utf8'));
 const el=id=>w.document.getElementById(id),click=id=>el(id).click();
 return{w,dom,el,click,advance(ms,level=db){db=level;for(let t=0;t<ms;t+=250){now+=250;loops.filter(Boolean).forEach(fn=>fn())}},stopped:()=>stopped};
}
const settle=()=>new Promise(r=>setImmediate(r));
test('manual default writes beta keys only; mode locked during recording',()=>{const a=setup({saved:{'piano-practice-timer-v1':'untouched1','piano-practice-timer-v2':'untouched2'}});assert.equal(a.el('timerMode').value,'manual');a.click('mainButton');assert.equal(a.el('timerMode').disabled,true);a.advance(2000);a.click('mainButton');a.click('saveSession');assert.equal(JSON.parse(a.w.localStorage.getItem('piano-practice-timer-beta')).sessions.length,1);assert.equal(a.w.localStorage.getItem('piano-practice-timer-v1'),'untouched1');assert.equal(a.w.localStorage.getItem('piano-practice-timer-v2'),'untouched2');a.dom.window.close()});
test('auto UI, pause/resume, export-compatible split records, microphone released',async()=>{const a=setup();a.el('timerMode').value='auto';a.el('timerMode').dispatchEvent(new a.w.Event('change'));a.click('mainButton');await settle();a.advance(122000,-80);assert.match(a.el('autoStatus').textContent,/一時停止/);const first=JSON.parse(a.w.localStorage.getItem('piano-practice-timer-beta')).sessions;assert.equal(first.length,1);a.advance(4000,-20);assert.match(a.el('autoStatus').textContent,/計測中/);a.advance(1000,-20);a.click('mainButton');a.click('saveSession');const records=JSON.parse(a.w.localStorage.getItem('piano-practice-timer-beta')).sessions;assert.equal(records.length,2);assert(records[1].startedAt>records[0].endedAt);assert.equal(a.w.localStorage.getItem('piano-practice-active-beta'),null);assert.equal(a.w.localStorage.getItem('piano-practice-auto-state-beta'),null);assert(a.stopped()>0);a.dom.window.close()});
test('microphone denial starts no timer and permits manual fallback',async()=>{const a=setup({denied:true});a.el('timerMode').value='auto';a.click('mainButton');await settle();assert.equal(a.el('mainButton').textContent,'開始');assert.match(a.el('autoStatus').textContent,/許可されません/);assert.equal(a.el('timerMode').disabled,false);assert.equal(a.w.localStorage.getItem('piano-practice-auto-state-beta'),null);a.dom.window.close()});
test('reload recovers last confirmed span and waits for explicit microphone reconnection',()=>{const a=setup({saved:{'piano-practice-auto-state-beta':JSON.stringify({state:'running',total:0,start:999999990000,last:999999995000})}});assert.match(a.el('autoStatus').textContent,/監視中断/);assert.equal(a.el('resumeAuto').hidden,false);assert.equal(a.el('timer').textContent,'00:00:05');assert.equal(JSON.parse(a.w.localStorage.getItem('piano-practice-timer-beta')).sessions[0].durationMs,5000);a.dom.window.close()});
test('v1/v2 JSON import uses isolated beta storage',async()=>{const a=setup();const sessions=[{id:'old',startedAt:999999990000,endedAt:999999995000,durationMs:5000,note:'音階 🎹'}];Object.defineProperty(a.el('backupFile'),'files',{value:[{text:async()=>JSON.stringify({app:'PianoTrack',version:1,schemaVersion:1,sessions})}]});a.el('backupFile').dispatchEvent(new a.w.Event('change'));await settle();a.click('confirmImport');assert.deepEqual(JSON.parse(a.w.localStorage.getItem('piano-practice-timer-beta')).sessions,sessions);a.dom.window.close()});
test('all runtime asset references are inside beta and exist',()=>{const doc=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8')).window.document;for(const el of doc.querySelectorAll('[src],link[href]')){const ref=el.getAttribute('src')||el.getAttribute('href');assert(!ref.includes('..'),ref);assert(!ref.startsWith('/'),ref);assert(fs.existsSync(path.join(root,ref)),ref)}for(const icon of JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'))).icons){assert(!icon.src.includes('..'));assert(fs.existsSync(path.join(root,icon.src)))} });
test('pagehide releases microphone and freezes at last confirmed sample',async()=>{const a=setup();a.el('timerMode').value='auto';a.click('mainButton');await settle();a.advance(2000);a.w.dispatchEvent(new a.w.Event('pagehide'));assert.match(a.el('autoStatus').textContent,/監視中断/);assert(a.stopped()>0);const elapsed=a.el('timer').textContent;a.advance(4000);assert.equal(a.el('timer').textContent,elapsed);a.dom.window.close()});
test('manual forgotten timer can be saved with a corrected end time',()=>{const a=setup({saved:{'piano-practice-active-beta':String(1000000000000-18000000)}});assert.equal(a.el('forgotDialog').open,true);const end=1000000000000-600000;const d=new Date(end),z=n=>String(n).padStart(2,'0');a.el('forgotEnd').value=`${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`;a.click('saveForgot');assert.equal(a.el('forgotDialog').open,false);assert.equal(a.w.localStorage.getItem('piano-practice-active-beta'),null);assert(JSON.parse(a.w.localStorage.getItem('piano-practice-timer-beta')).sessions[0].endedAt<=end);a.dom.window.close()});
